### ISSUE TITLE
[Feature Request] PF2e Interactive Token Tooltip Subtitles Change

### ISSUE THREAD

**Issue by ottyn** [Rowiz49/pf2e-wands-and-scrolls#11]
**Is your feature request related to a problem? Please describe.**
No issues currently with the module.  Scrolls/Wands currently show up on the PC sheet and work perfectly from the PC sheet.

When using PF2e Interactive Token Tooltip module, the spells all get jumbled together in the spell list.  Scroll/Wand spells show up with a subtitle of "Prepared" the same as regular prepared spells.

**Describe the solution you'd like**
Is there a way to have the subtitle of "Prepared" changed to "Wand" or "Scroll" in the tooltip to differentiate them? 

**Additional context**
Screen shot of the spells tab in ITT.  For instance the Rank 1 and Rank 2 Mending spells in the list are from Scrolls on the PC inventory.  While Enfeeble and Grim Tendrils spells are from a Staff prepared with PF2e Dailies module and show "Staff" below in the subtitle.

![image](https://github.com/Rowiz49/pf2e-wands-and-scrolls/assets/97130150/3e6b058c-8e42-4e57-8f8a-38e682d463cf)

**Comment by Rowiz49** [comment]
I'll look into fixing it :)
