### ISSUE TITLE
Feedback / Feature Requests

### ISSUE THREAD

**Issue by TiloBuechsenschuss** [Rowiz49/pf2e-wands-and-scrolls#2]
This is a great module and already provides quite a bit of utility! Thanks a bunch!

Here's some feedback:

- Maybe add a note that the spell was cast from an item? Could be useful for the GMS to make it clearer what's happening.
- Specific wands (like Shardstorm) don't seem to work yet
- Maybe add an option not to auto-delete the scrolls, but add a button to chat to delete the item? That way you don't use scrolls by accident and have to re-create them.

**Comment by Rowiz49** [comment]
Hi! Thanks for the feedback.
The first one is definitely doable, as is the last one though I will probably use a dialog instead of a chat message.
Speciality wands are not considered consumables by the system and usually modify the effects of spells, they are not planned for now.
