### ISSUE TITLE
[Feature Request] Setting whether you need to be able to cast the spell or not / support for Trick Magic Item

### ISSUE THREAD

**Issue by serbandr** [Rowiz49/pf2e-wands-and-scrolls#8]
I gave everybody Trick Magic Item as a free feat in my games, but it seems like Wands and Scrolls don't show up if they can't cast them by default. Maybe add a toggle in the game settings on whether that should apply or not (for people who choose to ignore requirements altogether) or at least have them show up if a player has the Trick Magic Item feat?

**Comment by Rowiz49** [comment]
Thanks for noticing! A fix is on the way so that the module correctly understands the trick magic item feat.
